### ISSUE TITLE
Script error on removing a chart from DOM

### ISSUE THREAD

**Issue by ilyavf** [bitovi-components/bit-c3#24]
See this [jsbin](http://jsbin.com/vavinow/9/edit?html,console,output).

When chart is removed from DOM its  [column/viewmodel unload function](https://github.com/bitovi-components/bit-c3/blob/master/src/data/column/viewmodel.js#L40) calls `c3_chart_internal_fn.unload` which refers to `$$.data.targets`. But `$$.data` is null and this causes an exception.

**Comment by phillipskevin** [comment]
Is this the same as https://github.com/bitovi-components/bit-c3/issues/21?

**Comment by ilyavf** [comment]
Yes.

**Comment by phillipskevin** [comment]
I'll close #21 since this has a better description / example.

**Comment by ilyavf** [comment]
OK. I will add a test and will try to fix this.

**Comment by ilyavf** [comment]
The reason for the exception is that on `bit-c3`'s `remove` event we call `c3`'s `this.destroy()` which cleans up its internal properties (including `this.data`). But then `remove` event of `bit-c3-data-column` gets fired which calls c3's `this.unload` method, but the chart is already "destroyed".

**Comment by ilyavf** [comment]
Fixed.
