### ISSUE TITLE
CanJS 4 compatibility?

### ISSUE THREAD

**Issue by MarcGodard** [bitovi-components/bit-c3#42]
Hi guys, can someone help make this canJs 4 compatible?

**Comment by justinbmeyer** [comment]
It's unlikely to be prioritized by the OS team in the next 6 weeks. We will happily accept a patch. Or you can come to the next survey meeting and promote this feature.

**Comment by MarcGodard** [comment]
@justinbmeyer thanks, I might work on it soon.

**Comment by ilyavf** [comment]
I can help with this.

**Comment by MarcGodard** [comment]
I have moved onto version 5 of can. Closing for now.
